### ISSUE TITLE
How can I get the CLC_100m_colmap.json?

### ISSUE THREAD

**Issue by GIShkl** [Lkruitwagen/deepsentinel#9]
When I run your code,I have a question,How can I get the CLC_100m_colmap.json?
Thank you!

**Comment by Lkruitwagen** [comment]
Hi! Apologies, I keep it in the `data/` folder but I can see that that might not be helpful. Have added it to `conf/`: https://github.com/Lkruitwagen/deepsentinel/blob/master/conf/CLC_100m_colmap.json

**Comment by hukelin** [comment]
Thank you very much!
By the way,when will you be able to provide a pre-training model?

**Comment by Lkruitwagen** [comment]
thanks for your interest! I'd like to release something a bit more 'official' whose performance I can vouch for, but I've just opened the experiments bucket for public read: https://console.cloud.google.com/storage/browser/deepsentinel-models. 
These are the model runs that give the results that can be found in the paper:
```
  VAE:
    resnet18: 9
    resnet18attn: 27
    resnet34: 20
  contrastive_loss:
    resnet18: 2
    resnet18attn: 28
    resnet34: 22
  none:
    resnet18: 3
    resnet18attn: 25
    resnet34: 21
  tile2vec:
    resnet18: 13
    resnet18attn: 26
    resnet34: 18
```
Let me know if you have access issues or any other questions!
